runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: templates/main.html
  upload: templates/main.html

- url: /(.*\.(js|css))$
  static_files: static/\1
  upload: static/.*\.(js|css)$
